using System.Collections.Generic;

namespace MyFace.Services;

public record OnionMonitorSeed(string Name, string Category, string Url);

public static class OnionMonitorSeedData
{
    public static IReadOnlyList<OnionMonitorSeed> All { get; } = new List<OnionMonitorSeed>
    {
        // Markets
        new("dark matter", "Markets", "http://darkmmka22ckaagrnkgyx6kba2brra3ulhz3grfo4fz425nr7owcncad.onion"),
        new("dark matter", "Markets", "http://darkmat3kdxestusl437urshpsravq7oqb7t3m36u2l62vnmmldzdmid.onion"),
        new("dark matter", "Markets", "http://darkmmk3owyft4zzg3j3t25ri4z5bw7klapq6q3l762kxra72sli4mid.onion"),
        new("drughub", "Markets", "http://drughub666py6fgnml5kmxa7fva5noppkf6wkai4fwwvzwt4rz645aqd.onion/"),
        new("torzon", "Markets", "http://nwsjsb3iwy3vep74gzbpue4b5ofe7eyyijxsdnifloly47uoqfpf7zad.onion"),
        new("torzon", "Markets", "http://torzon4kv5swfazrziqvel2imhxcckc4otcvopiv5lnxzpqu4v4m5iyd.onion/"),
        new("black ops", "Markets", "http://blackops3zlgfuq4dg4yrtxoe57u3sxfa34kqzbooqbovutleqhf3zqd.onion"),
        new("black ops", "Markets", "http://blackops66p7edjocooiipudvefdhupk27pi4y72iwnbbjvccky646yd.onion"),
        new("nexus", "Markets", "http://nexusabcdkq4pdlubs6wk6ad7pobuupzoomoxi6p7l32ci4vjtb2z7yd.onion/"),
        new("nexus", "Markets", "http://nexusb2l7hog66bnzz5msrz4m5qxj7jbi7aah3r65uzydy5mew2fu3id.onion/"),
        new("MarsMarket", "Markets", "http://d266wy5xjhsgd5y5t3lwhdstzhfahiu2hoouur64vvbbao6a3sjythqd.onion"),
        new("MarsMarket", "Markets", "http://mars24pazjige72veied4awxfb6gtkjauij7qkofveula7gc6fljy4qd.onion"),
        new("MarsMarket", "Markets", "http://marsautbkjnujgun5y2xfn5eli2zrdathxbj6z75zbjxyxb5qbidabad.onion"),
        new("atlas", "Markets", "http://atlasgooo2pie5vyvwbt35zvfsiiy3va7tirvbe5ocvjugq7lggxlmyd.onion/"),
        new("vortex", "Markets", "http://bar47oupp7kn2idtplbngebrtlhurfp5p4irvwngdkj2ynkc46jqihad.onion/"),
        new("vortex", "Markets", "http://mq7ozbnrqdjc6cof3yakegs44kmo6vl3ajcyzdeya3zjtmi65jtmwqid.onion/"),
        new("prime", "Markets", "http://primeynxn52jsv3d7mbq2zoehoikid7kv5gv7t3p3n2qeeqdgicxh5yd.onion"),
        new("omega", "Markets", "http://omega7eye5ar3rkrhfr5odhzmlft7mrygp76fuqkh4kian73nd3b7hyd.onion"),
        new("omega", "Markets", "http://m22jreil42iomvlkzitrkfcmd2g3c2qoznufe53t3kxicgjmfjcckmyd.onion"),
        new("cannaexpress", "Markets", "http://cannaexsunpnqjwy4i4bafbqgfsnn7lwnsf6azqgcaoog5d2i3qw2uyd.onion"),
        new("cannaexpress", "Markets", "http://cannaex7sxdz3fy3bhyoaagwr5hhb64oabqllb7fpqvl3qwafmxxdhqd.onion"),
        new("euphoria", "Markets", "http://euphor2ivtwosiz6zspq7rdzzmyyo5nvr76qtgc473e2hnhffsred6qd.onion"),
        new("euphoria", "Markets", "http://euphorialth2wxqjd2y3mmenyquhs7yj26hvtpbf7zhyfmed7752srid.onion"),
        new("shadow x", "Markets", "http://shadowxn3o3kvvkbjyaoe33emqxrtadijp7xybizbht2thb6x5dvfhad.onion"),
        new("dream v2", "Markets", "http://dreav274kne7kisdblemfliplkp3x7mxghd4p7nspcuwcehizr4ia5ad.onion/"),
        new("dream v2", "Markets", "http://dreav27yxpeipp3v3gplqgdohfgycalx2ag6gcqnceiajqe2pmzb6cqd.onion/"),
        new("kerberos", "Markets", "http://kerberosazmnfrjinmftp3im3cr7hw4nxbavm4ngofn64g24be7h3kqd.onion"),
        new("thor market", "Markets", "http://vck75uosucwzxgyp6yofroujgtasyuubkem7jh65r5ha5fmb6ztv6qqd.onion"),
        new("Argo Market", "Markets", "http://argo4y7i55eafmunecspkroynos76c7px7l6or3cdbpekltxqlxqjmqd.onion"),
        new("WeTheNorth Market", "Markets", "http://hn2paw7zaahbikbejiv6h22zwtijlam65y2c77xj2ypbilm2xs4bnbid.onion"),
        new("Awazon", "Markets", "http://awazonhndi7e5yfaobpk7j2tsnp4kfd2xa63tdtzcg7plc5fka4il4ad.onion"),
        new("Awazon", "Markets", "http://awazonmphskqrqr5fquam6h24dcifybo4wlzqzlw52edkn3nzfnmh6qd.onion"),
        new("Market of Eden", "Markets", "http://eden666otrbusyiopuvynvvdbzay2pqgsru6fymjlnukmizum4hewwad.onion"),
        new("Impact Market", "Markets", "http://4i7npytmp54nynycvnts6yfbklafw5qp6qqexrlacdd7gp4leeimksad.onion/"),
        new("warpzone", "Markets", "http://warpzonvz5ldennsbrkymt5d66ab5i25puaghgouw3fekcer2bxukgid.onion"),
        new("DrugTown", "Markets", "http://drugtowniiwgnpiyljq7t7dhuaa4hwxzgux2ou4h7nn7hzfzhtkjq3id.onion"),
        new("IDC Reborn", "Markets", "http://idcre2nx5m2gcgcnbzh6hjjezvlgywc6wu5gkconbr3wmgt22yst5ayd.onion"),
        new("Catharsis", "Markets", "https://catharibrmbuat2is36fef24gqf3rzcmkdy6llybjyxzrqthzx7o3oyd.onion/"),

        // Shops
        new("tribe seuss", "Shops", "http://eisrgs2wyyzaxemtaof3n2kqqxuxdx3y7r5vwfi7rukn3z7owxweznid.onion"),
        new("tribe seuss", "Shops", "http://dreadytofatroptsdj6io7l3xptbet6onoyno2yv7jicoxknyazubrad.onion/d/Tribe_Seuss"),
        new("Thebreakingbad", "Shops", "http://thebb3kuusuzxf26mqt5ugcyypzznfux7zvj6rlj5j64m3qg7lswxfad.onion/"),
        new("we are amsterdam", "Shops", "http://waa2dbeditmgttutm4m64jvwirmwtirhbuupngbhheddadyojgjsttid.onion"),
        new("we are amsterdam", "Shops", "http://dreadytofatroptsdj6io7l3xptbet6onoyno2yv7jicoxknyazubrad.onion/d/weareamsterdam/"),
        new("Filthy Fellas Vendor", "Shops", "http://ffelas6vkwdpbkc3mmoeqs36e3o2qef662ypzii4hx5ln6kecu2bwsyd.onion"),
        new("brightstar fountain", "Shops", "http://bfountainey5r3uxxfbck2wrrkwifasqitsb3sw33siq7bmpd6fpn5yd.onion"),
        new("brightstar fountain", "Shops", "http://flowersr4graduitzftbqphrl2s56yxkmgeehjkzj4ndfx4ex64xgqid.onion"),
        new("TopShellNL", "Shops", "http://zqnepw2dvsjtdjypbwurugtp3g46am55ugbx2wc2o4dsvuayamhtavqd.onion/"),
        new("TopShellNL", "Shops", "http://c5p4khnw66o6mrjpzxoszn5jqlqeynw75s5jf6whzts2g74dd4bvqxid.onion/"),
        new("TheGodFather", "Shops", "http://tgfarzpxl5yhlo3x2cyg62zsiac73brkfpsip4a3rpidghcrazmwk3qd.onion/"),
        new("Hellbin shop", "Shops", "http://hellbinuhs3hobszpwexcpqapmznqopmw2aeyzzmw4jssmy4e7msgdyd.onion"),
        new("Polar Labz", "Shops", "http://polar6264tpzrdlm4zskrt6daedffgr7veatrcfqw6i5u7jsql3365qd.onion"),
        new("Polar Labz", "Shops", "http://polar2673p73mqifgy2mkpllpjzofoziia5sclxvfaj372pbw3cndaad.onion"),
        new("JosephStalinCoba", "Shops", "http://hcze7i4zspyl2c4mime3ff7u4iex3vfvna6rqe7j3svyj3pqw5xqjaqd.onion/"),
        new("Doraemon Shop", "Shops", "http://doraemonr5dsozne3wj5hzdu6d2pb3eadiw56l2kcfqqqgbhlcxhieyd.onion"),

        // Forums
        new("dread", "Forums", "http://dreadytofatroptsdj6io7l3xptbet6onoyno2yv7jicoxknyazubrad.onion/"),
        new("dread", "Forums", "http://g66ol3eb5ujdckzqqfmjsbpdjufmjd5nsgdipvxmsh7rckzlhywlzlqd.onion/"),
        new("pitch", "Forums", "http://pitchprash4aqilfr7sbmuwve3pnkpylqwxjbj2q5o4szcfeea6d27yd.onion/"),
        new("pitch", "Forums", "http://pitchzzzoot5i4cpsblu2d5poifsyixo5r4litxkukstre5lrbjakxid.onion/"),
        new("breaking bad", "Forums", "http://bbzzzsvqcrqtki6umym6itiixfhni37ybtt7mkbjyxn2pgllzxf2qgyd.onion/"),
        new("darknet army", "Forums", "http://darknet77vonbqeatfsnawm5jtnoci5z22mxay6cizmoucgmz52mwyad.onion/"),
        new("germania", "Forums", "http://germania7zs27fu3gi76wlr5rd64cc2yjexyzvrbm4jufk7pibrpizad.onion/"),
        new("cebulka", "Forums", "http://cebulka7uxchnbpvmqapg5pfos4ngaxglsktzvha7a5rigndghvadeyd.onion/"),
        new("the secret garden", "Forums", "http://gardeni2xtbqdpn3mndvod5rzewor2rlo2g5iuyniqwd7vbyt7cwcrqd.onion"),
        new("the secret garden", "Forums", "http://gardenjsprbg5fchsmofxdjsti76dd7use3v4q4z2suqfgeytjylliid.onion"),
        new("exploit.in", "Forums", "http://exploitivzcm5dawzhe6c32bbylyggbjvh5dyvsvb5lkuz5ptmunkmqd.onion/"),

        // Services
        new("infinity", "Services", "http://exchanger.gyrwc2fhteu3jvpf5hywojfumxjjxplm2vkgcy4tziwpqaaz2wtirzqd.onion/"),
        new("infinity", "Services", "http://exchanger.dhme3vnfeleniirt5nxuhpmjsfq5srp44uyq2jyihhnrxus7ibfqhiqd.onion/"),
        new("openmonero", "Services", "http://fgssv2btn4f4gopdtka245bihx4eow2iquemikpqumxxemnjev6sjbyd.onion/"),
        new("get monero", "Services", "http://monerotoruzizulg5ttgat2emf4d6fbmiea25detrmmy7erypseyteyd.onion"),
        new("feather", "Services", "http://featherdvtpi7ckdbkb2yxjfwx3oyvr3xjz3oo4rszylfzjdg6pbm3id.onion/"),
        new("coin wallet", "Services", "https://coinspacezp5mmyuicbz2hoafbnduj4vzkttq3grn5mnwdue5t343zid.onion"),
        new("mullvad vpn", "Services", "http://o54hon2e2vj6c7m3aqqu6uyece65by3vgoxxhlqlsvkmacw6a7m7kiad.onion/"),
        new("airvpn", "Services", "http://airvpn3epnw2fnsbx5x2ppzjs6vxtdarldas7wjyqvhscj7x43fxylqd.onion/"),
        new("cryptostorm", "Services", "http://stormwayszuh4juycoy4kwoww5gvcu2c4tdtpkup667pdwe4qenzwayd.onion/"),
        new("morke", "Services", "http://6n5nbusxgyw46juqo3nt5v4zuivdbc7mzm74wlhg7arggetaui4yp4id.onion"),
        new("cockbox", "Services", "http://dwtqmjzvn2c6z2x462mmbd34ugjjrodowtul4jfbkexjuttzaqzcjyad.onion/"),
        new("hostmenow", "Services", "http://hostqfzelpvo643zinnyfwlwv2ujdvadxh24qjlc4up242peackq5pid.onion/"),
        new("whonix", "Services", "http://www.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion/"),
        new("qubes os", "Services", "http://qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/"),
        new("tor project", "Services", "http://2gzyxa5ihm7nsggfxnu52rck2vv4rvmdlkiu3zzui5du4xyclen53wid.onion/"),
        new("KYCNOTME", "Services", "http://kycnotmezdiftahfmc34pqbpicxlnx3jbf5p7jypge7gdvduu7i6qjqd.onion/"),
        new("daunt", "Services", "http://dauntdatakit2xi4usevwp3pajyppsgsrbzkfqyrp6ufsdwrnm6g5tqd.onion"),
        new("tor.taxi", "Services", "http://tortaxi2dev6xjwbaydqzla77rrnth7yn2oqzjfmiuwn5h6vsk2a4syd.onion/"),
        new("darknet trust", "Services", "http://dntrustmuq5ccf3lygrnhsprpdliakq7r2ljsspczmdsslj5wl4teeid.onion/"),
        new("Skout", "Services", "http://skoutchtiq6i473shdg2ycebalkqherg2ham2suvcoto6wtns5fpjvid.onion/"),
        new("narcoogle", "Services", "http://narcooqom5mfevbeb6gck5tg5y2g2f5grywcu7cp4b3bvsmlvph66wqd.onion/"),
        new("darksearch", "Services", "http://darkzqtmbdeauwq5mzcmgeeuhet42fhfjj4p5wbak3ofx2yqgecoeqyd.onion/"),
        new("tor times", "Services", "http://tortimeswqlzti2aqbjoieisne4ubyuoeiiugel2layyudcfrwln76qd.onion/"),
        new("the opsec manual", "Services", "http://jqibjqqagao3peozxfs53tr6aecoyvctumfsc2xqniu4xgcrksal2iqd.onion"),
        new("DarknetPedia", "Services", "http://2332lbt55y2sh2mmlusktrhwd23mvw2ptimgg623sr6h3ywzpnoe2qqd.onion"),
        new("DarknetPedia", "Services", "http://ronk2i5vgkone6erhu6yjezkq3ingehtzpifxuzlpqq6tfxxwf7iz7qd.onion"),
        new("Amnesia", "Services", "http://amnesia6iuqn46eyzcgymhzpom3gkqpj6yxacdpvu4mbq7sgskn6hvid.onion/"),
        new("TorDotRun", "Services", "http://torrun2qbnatvz7teqdbrowcw3tzexpkbkac76romztnaq5ngqxyz5ad.onion/"),
        new("null world", "Services", "http://oqampqzctgkbq2yizpqdxlywidwgplilk3ccbhcxqm7gf6erafpkpjad.onion/"),
        new("the nihilism opsec", "Services", "http://blog.nowherejezfoltodf4jiyl6r56jnzintap5vyjlia7fkirfsnfizflqd.onion")
    };
}
