#!/bin/bash
set -euo pipefail

# Start test environment (Tor + MyFace web server)

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd ../.. && pwd)"
PUBLISH_DIR="$ROOT/publish-dev"
WEB_DLL="$PUBLISH_DIR/MyFace.Web.dll"
LOG_FILE="$ROOT/test-web.out"
PID_FILE="$ROOT/test-web.pid"
TORRC_TEST="$ROOT/tor/torrc.test"
TOR_LOG="$ROOT/tor/tor-test.log"
HS_TEST_DIR="$ROOT/tor/hidden_service_test"
HOSTNAME_FILE="$HS_TEST_DIR/hostname"

log() {
    printf '[TEST] [%s] %s\n' "$(date -u +%H:%M:%S)" "$*"
}

if [ ! -f "$WEB_DLL" ]; then
    echo "[fail] Test build not found. Run './scripts/test/deploy-test.sh' first" >&2
    exit 1
fi

if [ ! -f "$TORRC_TEST" ]; then
    echo "[fail] Test Tor config not found at $TORRC_TEST" >&2
    echo "       Run './scripts/test/setup-tor-test.sh' to create it" >&2
    exit 1
fi

# Start Tor for test
log "Starting Tor test hidden service..."
if pgrep -a -f -- "-f $TORRC_TEST" >/dev/null 2>&1; then
    log "Test Tor already running"
else
    tor --RunAsDaemon 1 -f "$TORRC_TEST" --Log "notice file $TOR_LOG"
    log "Tor started (log: $TOR_LOG)"
    sleep 2
fi

# Check for hostname
if [ -f "$HOSTNAME_FILE" ]; then
    ONION_HOSTNAME=$(tr -d '\r\n' < "$HOSTNAME_FILE")
    log "Test .onion address: $ONION_HOSTNAME"
else
    log "Warning: hostname file not yet generated by Tor"
fi

# Stop existing test server if running
if [ -f "$PID_FILE" ]; then
    OLD_PID=$(cat "$PID_FILE")
    if kill -0 "$OLD_PID" 2>/dev/null; then
        log "Stopping old test server (PID $OLD_PID)"
        kill "$OLD_PID" || true
        sleep 1
    fi
    rm -f "$PID_FILE"
fi

# Start Kestrel on test port
log "Starting MyFace test server on http://localhost:5001 ..."
cd "$PUBLISH_DIR"
ASPNETCORE_ENVIRONMENT=Test \
    ASPNETCORE_URLS=http://localhost:5001 \
    nohup dotnet "$WEB_DLL" > "$LOG_FILE" 2>&1 &

WEB_PID=$!
echo "$WEB_PID" > "$PID_FILE"

log "Test server started (PID: $WEB_PID)"
log "Web log: $LOG_FILE"
log ""
log "Test site running at:"
log "  - Local: http://localhost:5001"
if [ -n "${ONION_HOSTNAME:-}" ]; then
    log "  - Onion: http://$ONION_HOSTNAME"
fi
log ""
log "To stop: ./scripts/test/stop-test.sh"
